version: "2.29.2"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'

  service-finance-bot:
    build:
      dockerfile: ./Dockerfile_bot
      context: .
    image: service_finance_bot_img
    container_name: service-finance-bot
    restart: always
    env_file:
      - .env
    ports:
      - '8001:8000'

  service-finance-api:
    build:
      dockerfile: ./Dockerfile_api
      context: .
    image: service_finance_api_img
    container_name: service-finance-api
    restart: always
    env_file:
      - .env
    ports:
      - '8002:8000'

volumes:
  postgres_db:
    external: true

networks:
  default:
    name: local-network
    external: true
