FROM python:3.12-alpine

WORKDIR /app

ENV PYTHONPATH=/app:/app/src

RUN pip install -U pip & pip install pip-tools

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY ./src ./src

CMD ["python", "-m", "src"]

USER ${USER}:${USER}